#1 update cta text
samaSiriwardhanage/spotlights pull request #2
Opened 2022-06-16 00:47 UTC by samaSiriwardhanage

Resolves #1 

I would like to indicate that visitors can select videos by clicking arrows to the next screen, and either wait for the next video to play physically move to adjacent Spotlights.

### Acceptance Criteria

- [ ] Update call to action text to TAP LENS ON READER 
- [ ] Arrows that sit on either side of the Spotlights carousel to indicate the ability to select Spotlights

### Relevant design files
https://www.figma.com/file/r8dJf66KcjkRONvMTqd8rF/VE---Gallery?node-id=729%3A13076

### Testing instructions
Add a list of steps required to test the feature.
1. See the text that matches to the design.
2. See the arrows that sit on either side of the Spotlights carousel.

2022-06-16 02:25 UTC, sam-maher-acmi requested changes
As discussed, let's add some tests to make sure that our new change stays put.

Simon implemented a test you can reference here: https://github.com/ACMILabs/spotlights/pull/97/files#diff-848d5bb24167507f5fc0aca738023eb7f4ed34dbe519ef6aa75a8c7eff244508R47-R52

2022-06-21 03:05 UTC, sam-maher-acmi requested changes
Looking great! I can see one change we need to make however.

2022-06-21 03:05 UTC, ghost commented on app/static/index.js
> +  collect.innerHTML = "TAP LENS ON READER";
Looks great!

However I can see that we also need to update the collect text here: https://github.com/samaSiriwardhanage/spotlights/blob/d6e0db14ec60e7468e5243275bd9683319ae6883/app/static/index.js#L319-L323

2022-06-21 03:08 UTC, sam-maher-acmi commented on app/static/index.js
> +  collect.innerHTML = "TAP LENS ON READER";
@samaSiriwardhanage Have a look at how Simon implemented this by using a constant: https://github.com/ACMILabs/spotlights/pull/97/files#diff-419f549c39ea2e68a3d4d3d379938911b69065e2b3a698c5e46c5abe66d998b7R41

This way we only need to update the text in one place.

Let me know if you have any questions.

2022-06-21 03:37 UTC, samaSiriwardhanage commented on app/static/index.js
> +  collect.innerHTML = "TAP LENS ON READER";
@sam-maher-acmi I've added constant variable.

2022-06-21 23:03 UTC, sam-maher-acmi approved these changes, later dismissed
Looks good!

Thanks for the tests.

2022-06-21 23:07 UTC, sam-maher-acmi requested changes
Looking close!

Looks like some linting is failing: https://github.com/samaSiriwardhanage/spotlights/runs/6978216992?check_suite_focus=true

Test the linting locally with `make lintjs`

2022-06-22 00:19 UTC, sam-maher-acmi approved these changes
Perfect, nice work.

2022-06-22 00:37 UTC, merged