#1 Add scroll arrors
samaSiriwardhanage/spotlights pull request #4
Opened 2022-06-22 01:40 UTC by samaSiriwardhanage

Resolves #X

This is used to indicate to visitors that it is possible to select other spotlight videos from the same screen.

### Acceptance Criteria
- [ ] Add scroll arrows

### Relevant design files
* None

### Testing instructions
1. None

### DoD
* None

2022-07-05 23:13 UTC, sam-maher-acmi requested changes
Few small syntax changes.

2022-07-05 23:13 UTC, ghost commented on app/static/style.css
> +
Remove the empty lines underneath

2022-07-05 23:13 UTC, ghost commented on app/static/style.css
> +}
Add a newline here.

I hit this often, it's a little quirk of git - but good practice to add.
https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log

2022-07-06 02:24 UTC, samaSiriwardhanage commented on app/static/style.css
> +
Removed empty lines.

2022-07-06 02:24 UTC, samaSiriwardhanage commented on app/static/style.css
> +}
Added a newline.

2022-07-18 01:24 UTC, sam-maher-acmi approved these changes
Nice work, sorry for the delay on this one!

2022-07-18 01:37 UTC, merged